---
name: Git-CPAN-Patch
version: 0.1.2
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: Patch CPAN modules using Git
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Git-CPAN-Patch
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yanick/git-cpan-patch.git
requires:
  Parse::BACKPAN::Packages: 0
  Pod::Usage: 0
  autodie: 0
  perl: 5.10.0
provides:
  Git::CPAN::Patch:
    file: lib/Git/CPAN/Patch.pm
    version: 0.1.2
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
