---
abstract: 'Patch CPAN modules using Git'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
configure_requires:
  Module::Build: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-CPAN-Patch
provides:
  Git::CPAN::Patch:
    file: lib/Git/CPAN/Patch.pm
  Git::CPAN::Patch::Import:
    file: lib/Git/CPAN/Patch/Import.pm
requires:
  BackPAN::Index: 0.39
  CLASS: 0
  CPANPLUS: 0.84
  File::Path: 0
  File::Temp: 0.22
  File::chdir: 0
  File::chmod: 0
  Pod::Usage: 0
  autodie: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Git-CPAN-Patch
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yanick/git-cpan-patch.git
version: 0.4.1
